-- Enable the pgvector extension to work with face embeddings
create extension if not exists vector;

-- Faculties (e.g., Engineering, Business)
create table faculties (
  id bigint generated by default as identity primary key,
  name text not null
);

-- Batches (e.g., Batch 24, Spring 2025)
create table batches (
  id bigint generated by default as identity primary key,
  faculty_id bigint references faculties(id) on delete cascade not null,
  name text not null
);

-- Sections (e.g., Section A, Section B)
create table sections (
  id bigint generated by default as identity primary key,
  batch_id bigint references batches(id) on delete cascade not null,
  name text not null
);

-- Subjects (e.g., Data Structures, Calculus)
create table subjects (
  id bigint generated by default as identity primary key,
  section_id bigint references sections(id) on delete cascade not null,
  name text not null
);

-- Students
-- storing 512-dimensional vector for InsightFace (Buffalo_L)
create table students (
  id bigint generated by default as identity primary key,
  section_id bigint references sections(id) on delete cascade not null,
  name text not null,
  roll_no text not null,
  face_embedding vector(128),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Teachers
create table teachers (
  id bigint generated by default as identity primary key,
  profile_id uuid references profiles(id) on delete cascade not null,
  faculty_id bigint references faculties(id) on delete set null,
  employee_id text,
  is_active boolean default true,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Routines (Schedule)
create table routines (
  id bigint generated by default as identity primary key,
  subject_id bigint references subjects(id) on delete cascade not null,
  teacher_id bigint references teachers(id) on delete cascade not null, -- Links to teachers
  start_time time,
  end_time time,
  day_of_week text not null,
  unique(subject_id, day_of_week, start_time)
);

-- Attendance Logs
create table attendance_logs (
  id bigint generated by default as identity primary key,
  student_id bigint references students(id) on delete cascade not null,
  routine_id bigint references routines(id) on delete cascade not null,
  status text not null,
  confidence float,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
